### ISSUE TITLE
Error Not Found

### ISSUE THREAD

**Issue by T1MOXA** [RumbleFrog/FetchPData#4]
I decided to fix the plugin under csgo.
But for some reason it is not working...
When you go to the page - there is error "Not Found"

My code: 
http://kopy.io/LPJGw#Q4Cdc2Kzyk3CMt

**Comment by rumblefrog** [comment]
What's the URL? Also, can you check the log for any errors?

**Comment by rumblefrog** [comment]
My help with this is also limited, as I do not play nor run a CSGO server.

**Comment by T1MOXA** [comment]
> What's the URL? Also, can you check the log for any errors?
All links lead to this error.
No, in the logs there is nothing.

**Comment by T1MOXA** [comment]
I was able to fix this problem, but I have the following question...
How to remove a message with the text "Fetch a multidimensional JSON encoded array of basic game information"

**Comment by T1MOXA** [comment]
And another question...
How to remove a message with the text "Fetch a multidimensional JSON encoded array of basic game information"

**Comment by rumblefrog** [comment]
The only encoding for JSON is UTF-8, UTF-16 or UTF-32.

Also to remove that text, 

```
if (!Web_RegisterRequestHandler(Web_ID, OnWebRequest, "FetchGData", "Fetch a multidimensional JSON encoded array of basic game information")) {
	SetFailState("Failed to register request handler.");
}
```

Set to

```
if (!Web_RegisterRequestHandler(Web_ID, OnWebRequest, "FetchGData", " ")) {
	SetFailState("Failed to register request handler.");
}
```

**Comment by T1MOXA** [comment]
To fix the encoding I added "response.AddHeader(WebHeader_ContentType, "text/plain; charset=UTF-8");" for each request. 

If you remove all the data to look like this:

`if (!Web_RegisterRequestHandler(Web_ID, OnWebRequest)) {
	SetFailState("Failed to register request handler.");
}`

I still have the text http://SSMaker.ru/fbc3bc78/

**Comment by rumblefrog** [comment]
Jasson is already by default UTF-8 compliant, setting additional headers would be redundant. And if you insist on adding the header still, the proper header would be ``application/json; charset=utf-8``

And for the description you're trying to remove for whatever reason: try " " with a space in it.

**Comment by T1MOXA** [comment]
Yes, it worked, thanks :)
